Feat 14,33 lobby modal redux store
Insamedkv/pointing-poker pull request #48
Opened 2021-09-10 10:58 UTC by upmyskills

1. resolve conflicts;
2. add connect to lobby modal;
3. add redux state for modal;
4. now we use reduxtoolkit functionality;
5. now we need only name of modal variant;
6. added aliases;

![изображение](https://user-images.githubusercontent.com/75721735/132843327-b5e4550a-6f50-406a-bd4a-059cb6058bcf.png)

2021-09-10 15:09 UTC, Cooler2012 approved these changes

2021-09-10 18:13 UTC, femiarkh requested changes
If importing redux toolkit, try to use its functionality, such as configureStore, createSlice, (later) createAsyncThunk. Do not put react component into your store. It should include serializable application state, as minimal amount of data as possible.

2021-09-10 18:13 UTC, femiarkh commented on src/components/Modal/Components/ModalBody/Components/LobbyContent/LobbyContent.tsx
> +  const { modal } = useTypedSelector((state) => state);
Please never do that. Do not get the whole state with `useSelector`, get the only piece you need.

2021-09-10 18:13 UTC, femiarkh commented on src/components/App.tsx
> +          onClick={() => dispatch(toggleModal(true, 'Connect to lobby', LobbyContent))}
There is no need to put the whole component into the store. You could just put there the name of the component, and and then get in in `ModalWindow` and render content by that name. There is also no need to pass `title` separately, since title is included in the content anyway.

2021-09-10 18:13 UTC, femiarkh commented on src/components/CustomInput/CustomInput.styles.ts
> +    boxShadow: `inset ${shadows[4]}, ${shadows[4]}`,
Nice usage of theme shadows with inset.

2021-09-10 18:13 UTC, femiarkh commented on src/components/CustomInput/CustomInput.styles.ts
> +      content: '"*"',
Why double quotes?

2021-09-10 18:13 UTC, femiarkh commented on src/components/FileChooser/FileChooser.styles.ts
> +      border: `1px solid ${grey.A200}`,
BTW there is nice grey `theme.palette.divider` color for separators.

2021-09-10 18:13 UTC, femiarkh commented on src/components/Modal/Components/ModalBody/Components/LobbyContent/LobbyContent.tsx
> +          {modal.title}:
See, you don't event need the whole `modal`, you need only `title`. I wouldn't make it a connected component at all.

2021-09-10 18:13 UTC, femiarkh commented on src/components/Modal/ModalWindow.tsx
> +          </Container> */}
Why leave this commented code?

2021-09-12 13:15 UTC, Insamedkv approved these changes

2021-09-12 19:28 UTC, Cooler2012 approved these changes

2021-09-13 19:18 UTC, femiarkh approved these changes

2021-09-13 20:05 UTC, merged